CREATE TABLE IF NOT EXISTS reports (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    report_date DATE NOT NULL,
    report_type VARCHAR(100) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    checksum CHAR(64) NOT NULL,
    events_total BIGINT DEFAULT 0,
    parser_status ENUM('pending','parsed','failed','duplicate') DEFAULT 'pending',
    error_message TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_reports_checksum (checksum),
    INDEX idx_reports_date (report_date),
    INDEX idx_reports_type (report_type),
    INDEX idx_reports_status (parser_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS report_events (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    report_id BIGINT NOT NULL,
    report_date DATE NOT NULL,
    report_type VARCHAR(100) NOT NULL,
    event_time DATETIME NULL,
    event_hour TINYINT NULL,
    events_count BIGINT DEFAULT 1,
    source_ip VARCHAR(45) NULL,
    source_host VARCHAR(255) NULL,
    source_user VARCHAR(255) NULL,
    source_country VARCHAR(150) NULL,
    destination_ip VARCHAR(45) NULL,
    destination_host VARCHAR(255) NULL,
    destination_port VARCHAR(80) NULL,
    destination_country VARCHAR(150) NULL,
    protocol_name VARCHAR(150) NULL,
    service_name VARCHAR(255) NULL,
    application_name VARCHAR(255) NULL,
    application_category VARCHAR(255) NULL,
    event_subtype VARCHAR(255) NULL,
    event_info VARCHAR(500) NULL,
    event_description TEXT NULL,
    bytes_rx BIGINT DEFAULT 0,
    bytes_tx BIGINT DEFAULT 0,
    bytes_total BIGINT DEFAULT 0,
    raw_payload JSON NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_report_events_report FOREIGN KEY (report_id) REFERENCES reports(id) ON DELETE CASCADE,
    INDEX idx_ev_report (report_id),
    INDEX idx_ev_date_type (report_date, report_type),
    INDEX idx_ev_time (event_time),
    INDEX idx_ev_hour (event_hour),
    INDEX idx_ev_source_ip (source_ip),
    INDEX idx_ev_dest_ip (destination_ip),
    INDEX idx_ev_dest_port (destination_port),
    INDEX idx_ev_user (source_user),
    INDEX idx_ev_service (service_name),
    INDEX idx_ev_app (application_name),
    INDEX idx_ev_src_country (source_country),
    INDEX idx_ev_dst_country (destination_country)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS import_logs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    source_file VARCHAR(255) NOT NULL,
    status ENUM('success','failed','duplicate') NOT NULL,
    message TEXT NULL,
    processed_files INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_import_logs_status (status),
    INDEX idx_import_logs_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
